### ISSUE TITLE
Feature request - API method for adding videos

### ISSUE THREAD

**Issue by DaneeSkripter** [Actulurus/cernyrob.in#1]
pls add api method for adding videos (I want to use this method in autokafka mobile app)

diky moc kluci <33333

**Comment by Actulurus** [comment]
ok bro lemme cook it up for ya bae

**Comment by Actulurus** [comment]
wait are tickets publicly visible???

**Comment by DaneeSkripter** [comment]
> wait are tickets publicly visible???
yes, they are 

> ok bro lemme cook it up for ya bae
oki, thanks 🙍🏿‍♂️

**Comment by Actulurus** [comment]
prisrali sme ti "list_answers" do api/get

**Comment by DaneeSkripter** [comment]
> prisrali sme ti "list_answers" do api/get

diky moc a udelate tu api metodu pro pridani videi?

**Comment by Actulurus** [comment]
nekdy navarim

**Comment by DaneeSkripter** [comment]
> nekdy navarim
asi uz neni treba, appka se nespis rusi

**Comment by Actulurus** [comment]
bruh moment

**Comment by StuckInVim-dev** [comment]
nah.
